sn4k3/UVtools

UVtools.Core/Layer/LayerIssue.cs
UVtools.Core/Layer/LayerManager.cs

This commit adds the ability to use the  4-connected neighbor approach rather than the 8-connected neighbor approach when
finding components in a layer during island evaluation.  This allows individual pixels or groups of pixels that are only touching on the diagonal of a single pixel to be evaluated independently for their island status rather than being treated as a single component.
This commit replaces the calls to findContour and drawContour in LayerManger with a call to connectedComponents, and updates the supporting logic to work with connectedComponents.  Only the section of the code dealing specifically with island
detection has been updated, so areas dealing with resinTraps, for example, still rely on findContour and drawContour, though, in theory, connectedComponets would also …

Support for 4-connected-neighbor island detection

---

UVtools.GUI/FrmMain.cs

Select color once per issue vs. once per pixel.  On large
Islands, this reduces layer rendering time by about an
order of magnitude or more.

Optimize showLayer call for Islands and Bounding

---

UVtools.GUI/FrmMain.cs

Cursor is changed to hand on SHIFT key, and pan mode
is also temporarily disabled.  Releasing SHIFT restores
default behavior.

Display hand cursor in select mode

---

UVtools.GUI/FrmMain.Designer.cs
UVtools.GUI/FrmMain.cs
UVtools.GUI/FrmMain.resx

Locking the auto-zoom level is now tied to click-hold of the
middle mouse button for 1 seconds rather than double-click
on middle mouse button.
This helps with accidental scrolling, as the middles mouse
button can sometimes be difficult to use.  Press-hold is
less error prone in this respect than double-click.

Change Zoom Level Lock to middle mouse click-hold

---

UVtools.GUI/FrmMain.Designer.cs
UVtools.GUI/FrmMain.cs

Tooltip is also updated to indicate middlemouse hold vs. double-click

Limit mouseHoldTimer to middle mouse button

---

UVtools.GUI/FrmMain.cs

When selecting issues using SHIFT in the layer preview, the selected issue doesn't update in the issue list until after shift is released.  This fix forces an immediate refresh of the issue list so that it updates as you click on issues in the layer preview rather than after SHIFT is released.
Also fixed some commented code for for clearing crosshairs before zoom so that it compiles when un-commented...but code
is still commented out in the commit.

Fix Issue List update on Layer Preview Select

---

UVtools.GUI/App.config
UVtools.GUI/Forms/FrmSettings.Designer.cs
UVtools.GUI/Forms/FrmSettings.cs
UVtools.GUI/Forms/FrmSettings.resx
UVtools.GUI/FrmMain.Designer.cs
UVtools.GUI/FrmMain.cs
UVtools.GUI/Properties/Settings.Designer.cs
UVtools.GUI/Properties/Settings.settings

-Adjusted wording for clarity across all tabs
-Adjusted capitilzation for consistency
-Color buttons are now 24x24 instead of 32x32.
-Misc adjustments to spacing and layouts.
-Replaced ZoomToFitiPringBounds checkbox with Combobox and mapped index to existing
config item.
-Added color selection for crosshair.

Settings Dialog Refresh

---

UVtools.GUI/Forms/FrmToolRepairLayers.Designer.cs
UVtools.GUI/Forms/FrmToolRepairLayers.cs
UVtools.GUI/Forms/FrmToolRepairLayers.resx

Detailed description and warning text in this dialog has been moved from main form into tooltips.  It's useful information for new users, but not needed to be visible each time repair is run.
Less frequently used settings for gap and noise removal iterations have been moved to an advanced settings group that
is hidden by default, and can be shown if changes in those settings is desired.  For many users, those advanced settings can be left on default and never adjusted.

Streamline Layer Repair Dialog

---

UVtools.GUI/Forms/FrmSettings.Designer.cs

After removal of the "Zoom out Large Issues" option in the settings checkbox, I was just glancing at the settings and thought the
Zoom group would look bettter with the dropdowns for Zoom In and Zoom Out at the top, and the checkbox option to enable zoom on single click at the bottom.
This is a very minor adjustment, so take it or leave it, either way is fine.  I went ahead and changed it in my fork just to see how it looked, liked it, so figured I'd submit.

Swap Location of Zoom out to Fit & Autozoom options

---

UVtools.GUI/App.config
UVtools.GUI/Forms/FrmSettings.Designer.cs
UVtools.GUI/Forms/FrmSettings.cs
UVtools.GUI/FrmMain.cs
UVtools.GUI/Properties/Settings.Designer.cs
UVtools.GUI/Properties/Settings.settings

The same MessageBox dialog in the pixel edit mode is used for both applying operations, and exiting pixel edit mode.
As a result, the text prompt feels a little out of context for the apply case, and this also results in pixel history getting cleared if you choose "No" on this dialog.  This makes sense if you are exiting pixel edit mode, but not if you just hit apply and changed your mind.
I added a separate dialog for the Apply case that only has the options "Yes/No".  Yes applies the changes, No behaves like Cancel.
Also added a new setting in the settings dialog so that pixel editor can be configured to exit after each apply operation.  I found I was applying operations and then going off and doing other things without realizing I was still in pixel edit mode, so thought this would be …

Fix inconsistencies on pixel edit apply confirm dialog

---

CompileWindows.bat
README.md

These are minor updates to guide building from source code. It isn't quite complete as I'm still getting an error when attempting to build
Error		Project '..\UVtools.Core\UVtools.Core.csproj' targets 'net5.0'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.8'.	UVtools.GUI			
PS I don't know why github thinks I changed the Why this project section in README.md as I only added a small section at the bottom of this file

Updates to building from source for Windows

---

UVtools.Core/FileFormats/CTBEncryptedFile.cs
UVtools.WPF/ConsoleArguments.cs

--decrypt-ctb <filepath> will decrypt all encrypted fields in the CTB. The file is replaced with the decrypted contents.
--encrypt-ctb <filepath> will encrypt header and footers of the CTB. No layer data is encrypted (not required). The file is replaced with the encrypted contents.

Add Encrypt/Decrypt CTB command line

---

UVtools.Core/Layer/LayerManager.cs
UVtools.WPF/MainWindow.LayerPreview.cs

This implements a novel resin/suction trap detection for MSLA sliced images.
It largely consists of 2 passes through the layers. 
The 1st pass processes the layers from the bottom to the top, keeping track of what areas in 
the previous layer are air (or connected to air in some way). The initial air map is derived from
the starting layer, by inverting the layer and then filling all external contours black (not air)
which results in an initial air map of everything that is not solid, or inside a solid, being considered
air. While traversing the layers, the air map is updated to include any new air regions, or hollow areas
that intersect with the air map (since while they are not air, they are connected to air). Any regions 
that do not overlap the air map are declared resin traps.
The 2nd …

New Resin Trap/Suction Cup detection algorithm

---

UVtools.Core/Layer/LayerManager.cs

Some sliced files can contain a completely empty layer. In such cases there are no "externals" and no "hollows", so appropriate null checks are needed.

 @tslater2006 Add missing null checks 

---

UVtools.Core/Managers/IssueManager.cs
UVtools.Core/Operations/OperationRepairLayers.cs
UVtools.WPF/MainWindow.Issues.cs

Both the repair operation as well as the deletion of an issue will now leverage common code for executing a repair. Repair operation will repair all suction cups, and deleting a specific suction cup will only repair that one.

Extract suction cup drilling to common function

---

UVtools.WPF/Controls/Tools/ToolCalculatorControl.axaml

(Fix) Corrected bottom lift unit label in light-off delay calculator

Correct bottom lift height typo in light off delay calculator

---

UVtools.Core/Operations/OperationPixelArithmetic.cs
UVtools.WPF/Controls/Tools/ToolPixelArithmeticControl.axaml

(Add) Random dithering - use for eliminating visual prominence of layer lines. Can also be used to add a microtexture to enhance paint bonding.
Add pixel arithmetic operation to randomly dither pixels based on
intensity. The random dithering significantly reduces layers lines and
also provides an excellent bonding surface for paints. Intial
implementation is based on a uniform random offset, will consider other algorithms in the future after practical testing.

Add corrosion effect

---

UVtools.Core/Managers/IssueManager.cs

Fix for edge case where a contour is in multiple groups and they get merged. Doesn't fix root cause of the contour being placed in 2 groups, but for the time being this works around it be deduping during the merge

Dedup contours during merging of resinTrapGroups.

---

build/platforms/linux/AppImage/UVtools.desktop

Restores ability to integrate AppImages into the desktop.
Older AppImages (2.2x) could be desktop-integrated by tools like AppImageLauncher. Since then, the desktop file was changed to include `Terminal=true`. For obvious reasons, terminal applications should not be integrated, and thus are ignored by libappimage-based tools.
Marks AppImage as UI tool, thus allowing AppImages to be integrated again.
The PR also removes the superfluous/broken `Path` setting.
(For the record, the desktop file template on the referenced wiki page is wrong there.)
Remove offending key(s) from the desktop file does the trick.
Didn't feel like I had to create an issue first, it's a minor fix, really.

Enable desktop integration for AppImages

---

README.md

Remove dupe Arch dependency from README
